name: 'AI Patch Doctor'
description: 'Zero-config CI check that detects AI API integration issues (429s, retry storms, streaming stalls, timeouts, cost explosions)'
author: 'Michael Brinkworth'

branding:
  icon: 'activity'
  color: 'blue'

inputs:
  telemetry:
    description: 'Enable anonymous telemetry (default: disabled)'
    required: false
    default: 'false'

runs:
  using: 'composite'
  steps:
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
    
    - name: Cache npm
      uses: actions/cache@v4
      with:
        path: ~/.npm
        key: ${{ runner.os }}-npm-ai-patch
        restore-keys: |
          ${{ runner.os }}-npm-
    
    - name: Run AI Patch Doctor
      shell: bash
      run: |
        if [ "${{ inputs.telemetry }}" = "true" ]; then
          npx -y ai-patch doctor --fix
        else
          npx -y ai-patch doctor --fix --no-telemetry
        fi
    
    - name: Display report in logs
      if: always()
      shell: bash
      run: |
        if [ -f report.md ]; then
          echo "## AI Patch Doctor Report"
          cat report.md
        else
          echo "⚠️ No report.md generated"
        fi
