# Example: How to use AI Patch Doctor in your repository
#
# This shows exactly how the action would run in someone's CI pipeline.
# Copy this to your repository as .github/workflows/ai-doctor.yml

name: AI Doctor

on:
  pull_request:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      # Use the AI Patch Doctor action
      - uses: michaelaccount2/ai-patch-doctor@v1
        # Optional: enable telemetry
        # with:
        #   telemetry: false
